KnowledgeHub.MVCCoreWebApplication/Controllers/ArticlesController.cs
using Humanizer;
using KnowledgeHub.DataAccess;
using KnowledgeHub.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

namespace KnowledgeHub.MVCCoreWebApplication.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly KnowldgeHubDbContext db;

        public ArticlesController(KnowledgeHub.DataAccess.KnowldgeHubDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int catagoryid=0)
        {

            //DateTime.Now.AddHours(-1).Humanize();

            var catagories = db.Catagories.ToList();

            ViewBag.CatagoryID = from sli in catagories
                                 select new SelectListItem { Value = sli.CatagoryID.ToString(), Text = sli.CatagoryName };


            List<Article> approvedArticles = null;
            if (catagoryid == 0)
            {
                // fetch all approved articles and pass to view
                approvedArticles = db.Articles.Include(a => a.Catagory).Where(a => a.IsApproved).ToList();
            }
            else
            {
                approvedArticles = db.Articles.Include(a => a.Catagory).Where(a => a.IsApproved && a.CatagoryID == catagoryid).ToList();
            }
            return View(approvedArticles);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var catagories = db.Catagories.ToList();

            ViewBag.CatagoryID = from sli in catagories
                                 select new SelectListItem { Value = sli.CatagoryID.ToString(), Text = sli.CatagoryName };

            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Article article)
        {
            if (!ModelState.IsValid)
                return View(article);
            article.SubmittedBy = User.Identity.Name;
            db.Articles.Add(article);
            db.SaveChanges();

            //return RedirectToAction("Index");
            TempData["msg"] = $"{article.Title} is created successfully";
            return RedirectToAction("Create");
        }

        public IActionResult ApproveReject()
        {
            var unApprovedArticles = db.Articles.Include(a => a.Catagory).Where(a => !a.IsApproved).ToList();
            return View(unApprovedArticles);
        }

        public IActionResult Approve(List<int> articleid)
        {
            var articlesToApprove = db.Articles.Where(a => !a.IsApproved).ToList();
            foreach (var article in articlesToApprove)
            {
                foreach (var aid in articleid)
                {
                    if (article.ArticleID == aid)
                        article.IsApproved = true;
                }
            }
            db.SaveChanges();

            //SmtpClient
            //MailAddress
            //MailMessage

            return RedirectToAction("ApproveReject");
        }

        public IActionResult Reject(List<int> articleid)
        {
           
                foreach (var aid in articleid)
                {
                    var articleToReject = db.Articles.Find(aid);
                    db.Articles.Remove(articleToReject);
                }
            
                db.SaveChanges();

            return RedirectToAction("ApproveReject");
        }
    }
}

KnowledgeHub.MVCCoreWebApplication/ViewComponents/ArticlesCountViewComponent.cs
using KnowledgeHub.DataAccess;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace KnowledgeHub.MVCCoreWebApplication.ViewComponents
{
    public class ArticlesCountViewComponent : ViewComponent
    {
        public ArticlesCountViewComponent(KnowledgeHub.DataAccess.KnowldgeHubDbContext db)
        {
            Db = db;
        }

        public KnowldgeHubDbContext Db { get; }

        public IViewComponentResult Invoke(bool isApproved = false)
        {

            int count = 0;
            if (isApproved)
                count = Db.Articles.Count(a => a.IsApproved);
            else
                count = Db.Articles.Count();


            ViewBag.Count = count;
            return View(); // default.cshtml
        }

    }
}

KnowledgeHub.MVCCoreWebApplication/Views/Articles/ApproveReject.cshtml
@model IEnumerable<KnowledgeHub.Entities.Article>
@using Humanizer
@{
    ViewData["Title"] = "ApproveReject";
}

<h1>Approve / Reject Articles</h1>
  <form method="post">
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.ArticleID)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Catagory.CatagoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubmittedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateSubmitted)
            </th>
            
            
        </tr>
    </thead>
  
    <tbody>
        
@foreach (var item in Model) {
        <tr>
            <td>
                <input type="checkbox" name="articleid" value="@item.ArticleID"/>
                @*@Html.DisplayFor(modelItem => item.ArticleID)*@
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Title)*@
                <a href="@item.ArticleUrl" target="_blank">@item.Title</a>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.ArticleUrl)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                       
                @Html.DisplayFor(modelItem => item.Catagory.CatagoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmittedBy)
            </td>
            <td>
                    @{
                        var date = item.DateSubmitted.Humanize(false);
                    }
                @*@Html.DisplayFor(modelItem => item.DateSubmitted.ToString("MMM, dd yyyy"))*@
                <span>@date</span>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IsApproved)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
    
</table>

<input type="submit" asp-action="Approve" asp-controller="Articles" value="Approve" class="btn btn-info" />
<input type="submit" asp-action="Reject" asp-controller="Articles" value="Reject" class="btn btn-danger" />

</form>  

KnowledgeHub.MVCCoreWebApplication/Views/Articles/Create.cshtml
@model KnowledgeHub.Entities.Article

@{
    ViewData["Title"] = "Create";
}

<div class="alert alert-primary" role="alert">
  @TempData["msg"]
</div>


<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @* <div class="form-group">
                <label asp-for="ArticleID" class="control-label"></label>
                <input asp-for="ArticleID" class="form-control" />
                <span asp-validation-for="ArticleID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleUrl" class="control-label"></label>
                <input asp-for="ArticleUrl" class="form-control" />
                <span asp-validation-for="ArticleUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea rows=4 cols=60 asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatagoryID" class="control-label"></label>

               @* <select asp-for=CatagoryID  asp-items=@ViewBag.CatagoryID />*@
                @Html.DropDownList("CatagoryID")
                   
               @* <input asp-for="CatagoryID" class="form-control" />*@
                <span asp-validation-for="CatagoryID" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="SubmittedBy" class="control-label"></label>
                <input asp-for="SubmittedBy" class="form-control" />
                <span asp-validation-for="SubmittedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateSubmitted" class="control-label"></label>
                <input asp-for="DateSubmitted" class="form-control" />
                <span asp-validation-for="DateSubmitted" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsApproved" /> @Html.DisplayNameFor(model => model.IsApproved)
                </label>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KnowledgeHub.MVCCoreWebApplication/Views/Articles/Index.cshtml
@model IEnumerable<KnowledgeHub.Entities.Article>

@{
    ViewData["Title"] = "Index";
}
 <partial name="_TitlePartialView" />
 @* @{
        Html.RenderPartial("_TitlePartialView");
    }*@
    <vc:articles-count></vc:articles-count>
<h1>Browse Articles</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Index" asp-controller=Articles method="post">
            Select Catagory to Search : 
            @Html.DropDownList("CatagoryID")
            <input type="submit" value="Search" />
        </form>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.ArticleID)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
           @* <th>
                @Html.DisplayNameFor(model => model.ArticleUrl)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatagoryID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubmittedBy)
            </th>
           @* <th>
                @Html.DisplayNameFor(model => model.DateSubmitted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsApproved)
            </th>
            <th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           @* <td>
                @Html.DisplayFor(modelItem => item.ArticleID)
            </td>*@
            <td>
               @* @Html.DisplayFor(modelItem => item.Title)*@
               <a href="@item.ArticleUrl" target="_blank">@item.Title</a>
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.ArticleUrl)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.CatagoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmittedBy)
            </td>
           @*
            <td>
                @Html.DisplayFor(modelItem => item.DateSubmitted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsApproved)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>