KnowledgeHub.MVCCoreWebApplication/Controllers/ArticlesController.cs
using Humanizer;
using KnowledgeHub.DataAccess;
using KnowledgeHub.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

namespace KnowledgeHub.MVCCoreWebApplication.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly KnowldgeHubDbContext db;

        public ArticlesController(KnowledgeHub.DataAccess.KnowldgeHubDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int catagoryid=0)
        {

            //DateTime.Now.AddHours(-1).Humanize();

            var catagories = db.Catagories.ToList();

            ViewBag.CatagoryID = from sli in catagories
                                 select new SelectListItem { Value = sli.CatagoryID.ToString(), Text = sli.CatagoryName };


            List<Article> approvedArticles = null;
            if (catagoryid == 0)
            {
                // fetch all approved articles and pass to view
                approvedArticles = db.Articles.Include(a => a.Catagory).Where(a => a.IsApproved).ToList();
            }
            else
            {
                approvedArticles = db.Articles.Include(a => a.Catagory).Where(a => a.IsApproved && a.CatagoryID == catagoryid).ToList();
            }
            return View(approvedArticles);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var catagories = db.Catagories.ToList();

            ViewBag.CatagoryID = from sli in catagories
                                 select new SelectListItem { Value = sli.CatagoryID.ToString(), Text = sli.CatagoryName };

            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Article article)
        {
            if (!ModelState.IsValid)
                return View(article);
            article.SubmittedBy = User.Identity.Name;
            db.Articles.Add(article);
            db.SaveChanges();

            //return RedirectToAction("Index");
            TempData["msg"] = $"{article.Title} is created successfully";
            return RedirectToAction("Create");
        }

        public IActionResult ApproveReject()
        {
            var unApprovedArticles = db.Articles.Include(a => a.Catagory).Where(a => !a.IsApproved).ToList();
            return View(unApprovedArticles);
        }

        public IActionResult Approve(List<int> articleid)
        {
            var articlesToApprove = db.Articles.Where(a => !a.IsApproved).ToList();
            foreach (var article in articlesToApprove)
            {
                foreach (var aid in articleid)
                {
                    if (article.ArticleID == aid)
                        article.IsApproved = true;
                }
            }
            db.SaveChanges();

            //SmtpClient
            //MailAddress
            //MailMessage

            return RedirectToAction("ApproveReject");
        }

        public IActionResult Reject(List<int> articleid)
        {
           
                foreach (var aid in articleid)
                {
                    var articleToReject = db.Articles.Find(aid);
                    db.Articles.Remove(articleToReject);
                }
            
                db.SaveChanges();

            return RedirectToAction("ApproveReject");
        }
    }
}

KnowledgeHub.MVCCoreWebApplication/Controllers/CatagoriesController.cs
using KnowledgeHub.DataAccess;
using KnowledgeHub.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace KnowledgeHub.MVCCoreWebApplication.Controllers
{

    // CatagoriesController ctr = new CatagoriesController(new KnowldgeHubDbContext())
    [Authorize(Roles = "admin")]
    public class CatagoriesController : Controller
    {
        private readonly KnowldgeHubDbContext db;

        public CatagoriesController(KnowledgeHub.DataAccess.KnowldgeHubDbContext db)
        {
            this.db = db;
        }

       [AllowAnonymous]
        public IActionResult Index()
        {
            // fetch all catagories and display
            List<Catagory> catagories = db.Catagories.ToList();
            //ViewBag.Catagories = catagories;
            return View(catagories);
        }

        // /catagories/create
        public IActionResult Create()
        {
            // send a view to collect catagories information from user
            return View();
        }

        public IActionResult Save(Catagory catagory)
        {

            // Receive the data from view
            // validate the data
            //if(catagory.CatagoryName.Length <= 0 || catagory.CatagoryName == null)
            if(!ModelState.IsValid)
            {
                return View("Create");

            }
            // persist the data
            // KnowledgeHub.DataAccess.KnowldgeHubDbContext db = new DataAccess.KnowldgeHubDbContext();
            db.Catagories.Add(catagory);
            db.SaveChanges();
            // return a index view 
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            // fetch the catagory by id
            Catagory catagoryToDelete = db.Catagories.Find(id);
            if (catagoryToDelete == null)
                return NotFound();
            return View(catagoryToDelete);
            // pass the catagory obj to a view for confirmation
            // on confirmation delete the catagory and return to index

            
        }

        public IActionResult ConfirmDelete(int id)
        {
            // fetch the catagory by id
            Catagory catagoryToDelete = db.Catagories.Find(id);
            db.Catagories.Remove(catagoryToDelete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // fetch the catagory by id
            Catagory catagoryToEdit = db.Catagories.Find(id);
            if (catagoryToEdit == null)
                return NotFound();
            return View(catagoryToEdit);
        }
        [HttpPost]
        public IActionResult Edit(Catagory catagory)
        {
            if (!ModelState.IsValid)
                return View(catagory);
            db.Entry(catagory).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

KnowledgeHub.MVCCoreWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KnowledgeHub.MVCCoreWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Knowledge Hub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagories" asp-action="Create">Create Catagories</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagories" asp-action="Index">List Catagories</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Create">Submit Article</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Browse Article</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="ApproveReject">Approve Article</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Knowledge Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KnowledgeHub.MVCCoreWebApplication/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KnowledgeHub.MVCCoreWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background:yellow">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Knowledge Hub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagories" asp-action="Create">Create Catagories</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagories" asp-action="Index">List Catagories</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Create">Submit Article</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Browse Article</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="ApproveReject">Approve Article</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Knowledge Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KnowledgeHub.MVCCoreWebApplication/Views/Shared/_TitlePartialView.cshtml
<div class="alert alert-dark">

    <h1 class="display-4">Welcome to Knowledge Hub Portal</h1>
    <hr />
</div>